const userPrivacyZh = '''Meditor隐私政策

本政策是 Abandoft Studio（以下简称“开发者”）为处理您的个人信息而制定。

Meditor（以下简称为“本软件”）尊重并保护所有用户的个人隐私权。本软件会按照隐私政策的相关规定使用和披露您的个人信息。除隐私政策另有规定外，在未征得您事先许可的情况下，本软件不会将这些信息对外披露或向第三方提供。本软件会不时更新隐私政策。您在同意本软件服务使用协议之时，即视为您已经同意隐私政策全部内容。隐私政策属于本软件服务使用协议不可分割的一部分。

1. 适用范围

    * 用户使用本软件时产生的任何数据；

    * 本软件通过合法途径从商业伙伴处取得的用户个人数据。

2. 信息使用

    * 本软件不会主动向任何无关第三方提供、出售、出租、分享或交易您的个人信息，除非事先得到您的许可。如果您使用了软件内提供的云同步功能，因此产生的一切风险，包括但不限于数据泄露、损坏和丢失，均由您个人承担责任。

    * 本软件亦不允许任何第三方以任何手段主动收集、编辑、出售或者无偿传播您的个人信息。任何本软件平台用户如从事上述活动，一经发现，本软件有权立即终止与该用户的服务协议。

3. 信息披露

    在如下情况下，本软件将依据您的个人意愿或法律的规定全部或部分的披露您的个人信息：

    * 经您事先同意，向第三方披露；

    * 为提供您所要求的产品和服务，而必须和第三方分享您的个人信息；

    * 根据法律的有关规定，或者行政或司法机构的要求，向第三方或者行政、司法机构披露；

    * 如您出现违反有关法律、法规或者本软件服务协议或相关规则的情况，需要向第三方披露；

    * 如您是适格的知识产权投诉人并已提起投诉，应被投诉人要求，向被投诉人披露，以便双方处理可能的权利纠纷；

    * 其它根据法律、法规认为合适的披露。

4. 信息存储和交换

    本软件暂时不会收集和上传您的任何个人数据。

5. 信息安全

    * 作为一款工具类文本编辑软件，主要功能都是离线进行，因此本软件不强制用户注册账户进行登录。

    * 如开发者使用你的信息超出本政策目的或合理范围，开发者必须在变更使用目的或范围前，再次以APP内通知的形式告知并征得您的明示同意。

6. 本隐私政策的更改

    * 如果决定更改隐私政策，我们会在隐私政策网站、APP或我们认为适当的位置发布这些更改，以便您了解我们如何收集、使用您的个人信息，哪些人可以访问这些信息，以及在什么情况下我们会披露这些信息；

    * 开发者保留随时修改本政策的权利，因此请经常查看。如对本政策作出重大更改，开发者会通过隐私政策网站以通知的形式告知。请您妥善保护自己的个人信息，仅在必要的情形下向他人提供。如您发现自己的个人信息泄密，请您立即联络本软件客服，以便我们采取相应措施。

7. 使用SDK情况说明

    除软件开发工具外，本软件暂未使用任何第三方提供的SDK主动获取、收集或传播您的用户数据。

8. 其他

    如本隐私政策同时存在中文、英文等多个版本，以最新的中文版本为准。

9. 联系方式

    如有疑问或建议，请随时与开发者联系，可发送邮件至：moluopro@gmail.com。开发者将保留您发送的邮件，但仅用于回复您的疑问和建议，不会用于任何营销目的。

Abandoft Studio

更新时间：2023年1月15日

生效时间：2023年1月15日
''';

const userPrivacyEN = '''Meditor Privacy Policy

This policy has been developed by Abandoft Studio ("Developer") for the processing of your personal information.

Meditor (hereinafter referred to as "the Software") respects and protects the personal privacy of all users. The Software will use and disclose your personal information in accordance with the provisions of the Privacy Policy. Except as otherwise provided in the Privacy Policy, the Software will not disclose or provide such information to third parties without your prior consent. The Software may update the Privacy Policy from time to time. By agreeing to the Software Service Use Agreement, you are deemed to have agreed to the Privacy Policy in its entirety. The Privacy Policy is an integral part of the Software Service Use Agreement.

1. Scope of Application

    * Any data generated by the user when using the Software.

    * Personal data of the user obtained by the Software from business partners through legal means.

2. Use of Information

    * The Software will not actively provide, sell, rent, share or trade your personal information to any unrelated third party, unless prior permission is obtained from you. If you use the cloud synchronization function provided within the Software, all risks arising from it, including but not limited to data leakage, damage and loss, are your personal responsibility.

    * The Software also does not allow any third party to actively collect, edit, sell or distribute your personal information by any means without compensation. Any user of the Software platform who engages in the above activities, upon discovery, the Software has the right to immediately terminate the service agreement with such user.

3. Information Disclosure

    The Software will disclose your personal information, in whole or in part, in accordance with your personal wishes or as required by law, in the following circumstances.

    * disclosure to a third party with your prior consent.

    * it is necessary to share your personal information with a third party in order to provide the products and services you have requested.

    * Disclosure to third parties or administrative or judicial bodies in accordance with the relevant provisions of the law, or the requirements of administrative or judicial bodies.

    * Disclosure to third parties is required if you are in violation of relevant laws, regulations or this software service agreement or related rules.

    * If you are an eligible IPR complainant and have filed a complaint, disclosure to the respondent at the request of the respondent so that both parties can deal with possible rights disputes.

    * Other disclosures deemed appropriate in accordance with laws and regulations.

4. Information Storage and Exchange

    The Software will not collect and upload any of your personal data for the time being.

5. Information Security

    * As a tool-based text editing software, the main functions are performed offline, so the software does not force users to register an account for login.

    * If the developer uses your information beyond the purpose or reasonable scope of this policy, the developer must again inform and obtain your express consent in the form of an in-app notice before changing the purpose or scope of use.

6. Changes to this Privacy Policy

    * If we decide to change the Privacy Policy, we will post those changes on the Privacy Policy website, in the APP, or where we deem appropriate so that you are aware of how we collect and use your personal information, who has access to that information, and under what circumstances we disclose it.

    * The Developer reserves the right to change this Policy at any time, so please check back often. If significant changes are made to this policy, the developer will notify you by notice through the Privacy Policy website. Please protect your personal information properly and provide it to others only when necessary. If you find that your personal information has been compromised, please contact our software customer service immediately so that we can take appropriate measures.

7. Use of SDK

    Except for the software development tools, the software does not use any third-party SDK to actively obtain, collect or disseminate your user data.

8. Other

    If there are multiple versions of this privacy policy, such as Chinese and English, the latest Chinese version shall prevail.

9. Contact

    If you have any questions or suggestions, please feel free to contact the developer by sending an email to moluopro@gmail.com. The developer will keep the email you send, but will only use it to reply to your questions and suggestions, and will not use it for any marketing purposes.

Abandoft Studio

Updated: January 15, 2023

Effective: January 15, 2023
''';